- name: "Azure Diagnostic Settings Deletion"
  severity: "Medium"
  description: "Identifies the deletion of diagnostic settings in Azure, which send platform logs and metrics to different destinations. An adversary may delete diagnostic settings in an attempt to evade defenses."
  solution: "Ensure proper Registry permissions are in place to prevent adversaries from disabling or interfering with security/logging services. Ensure proper process and file permissions are in place to prevent adversaries from disabling or interfering with security/logging services. Deletion of diagnostic settings may be done by a system or network administrator. Verify whether the username, hostname, and/or resource name should be making changes in your environment. Diagnostic settings deletion from unfamiliar users or hosts should be investigated. If known behavior is causing false positives, it can be exempted from the rule."
  category: "Impair Defenses"
  tactic: "Defense Evasion"
  dataTypes: ["azure"]
  reference:
    - "https://attack.mitre.org/techniques/T1562/"
    - "https://attack.mitre.org/techniques/T1562/001/"
  frequency: 60
  cache:
    - allOf:
        - field: "logx.azure.resourceProviderName.value"
          operator: "::"
          value: azure.activitylogs
        - field: "logx.azure.operationName.value"
          operator: "::"
          value: "MICROSOFT.INSIGHTS/DIAGNOSTICSETTINGS/DELETE"
        - field: "logx.azure.status.value"
          operator: "::"
          value: Succeeded
      timeLapse: 60
      minCount: 1
      save:
        - field: "logx.azure.claims.ipaddr"
          alias: "SourceIp"
        - field: "logx.azure.caller"
          alias: "SourceUser"
