- name: "Azure Application Credential Modification"
  severity: "Medium"
  description: "Identifies when a new credential is added to an application in Azure An application may use a certificate or secret string to prove its identity when requesting a token. Multiple certificates and secrets can be added for an application and an adversary may abuse this by creating an additional authentication method to evade defenses or persist in an environment."
  solution: "Limit credential overlap across systems to prevent the damage of credential compromise and reduce the adversary's ability to perform Lateral Movement between systems. Application credential additions may be done by a system or network administrator. Verify whether the username, hostname, and/or resource name should be making changes in your environment. Application credential additions from unfamiliar users or hosts should be investigated. If known behavior is causing false positives, it can be exempted from the rule."
  category: "Use_Alternate_Authentication_Material"
  tactic: "Defense Evasion"
  dataTypes: ["azure"]
  reference:
    - "https://attack.mitre.org/techniques/T1550/"
    - "https://attack.mitre.org/tactics/TA0005/"
  frequency: 60
  cache:
    - allOf:
        - field: "logx.azure.resourceProviderName.value"
          operator: "::"
          value: azure.activitylogs
        - field: "logx.azure.operationName.localizedValue"
          operator: "::"
          value: "Update application - Certificates and secrets management"
        - field: "logx.azure.status.value"
          operator: "::"
          value: Succeeded
      timeLapse: 60
      minCount: 1
      save:
        - field: "logx.azure.claims.ipaddr"
          alias: "SourceIp"
        - field: "logx.azure.caller"
          alias: "SourceUser"
