- name: "User Added as Owner for Azure Application"
  severity: "Low"
  description: "Identifies when a user is added as an owner for an Azure application. An adversary may add a user account as an owner for an Azure application in order to grant additional permissions and modify the application's configuration using another account. "
  solution: "Audit local accounts permission levels routinely to look for situations that could allow an adversary to gain wide access by obtaining credentials of a privileged account. These audits should check if new local accounts are created that have not be authorized. Implementing LAPS may help prevent reuse of local administrator credentials across a domain"
  category: "Account Manipulation"
  tactic: "Persistence"
  dataTypes: ["azure"]
  reference:
    - "https://attack.mitre.org/techniques/T1098/"
  frequency: 60
  cache:
    - allOf:
        - field: "logx.azure.resourceProviderName.value"
          operator: "::"
          value: azure.auditlogs
        - field: "logx.azure.operationName.localizedValue"
          operator: "::"
          value: "Add owner to application"
        - field: "logx.azure.status.value"
          operator: "::"
          value: Succeeded
      timeLapse: 60
      minCount: 1
      save:
        - field: "logx.azure.claims.ipaddr"
          alias: "SourceIp"
        - field: "logx.azure.caller"
          alias: "SourceUser"
