- name: Microsoft 365 Exchange DKIM Signing Configuration Disabled
  severity: Medium
  description: "When it comes to protecting its users, Microsoft takes the threat of phishing seriously. Spoofing is a common technique that's 
    used by attackers. Spoofed messages appear to originate from someone or somewhere other than the actual source. This technique is often 
    used in phishing campaigns that are designed to obtain user credentials. The anti-spoofing technology in EOP specifically examines forgery of the From header in the message body (used to display the message sender in email clients). When EOP has high confidence that the From header is forged, the message is identified as spoofed.<br>
    Identifies when a DomainKeys Identified Mail (DKIM) signing configuration is disabled in Microsoft 365. With DKIM in
    Microsoft 365, messages that are sent from Exchange Online will be cryptographically signed. This will allow the
    receiving email system to validate that the messages were generated by a server that the organization authorized and not
    being spoofed."
  solution: "
    <ol>
    <li>An integral part of any anti-spoofing effort is the use of email authentication (also known as email validation) by SPF, DKIM, and DMARC records in DNS. You can configure these records for your domains so destination email systems can check the validity of messages that claim to be from senders in your domains. For inbound messages, Microsoft 365 requires email authentication for sender domains.</li>
    <li>Review spoofed messages from senders in internal and external domains during the last 7 days, and allow or block those senders.</li>
    <li>Allow or block spoofed senders in the Tenant Allow/Block List. When you override the verdict in the spoof intelligence insight, the spoofed sender becomes a manual allow or block entry that only appears on the Spoof tab in the Tenant Allow/Block List. You can also manually create allow or block entries for spoof senders before they're detected by spoof intelligence.</li>
    <li>Turn on Anti-phishing policies In EOP and Microsoft Defender for Office 365</li>
    </ol>
    <strong>Potential alse positive: </strong> Disabling a DKIM configuration may be done by a system or network administrator. 
    Verify that the configuration change was expected. Exceptions can be added to this rule to filter expected behavior."
  category: "Phishing"
  tactic: "Spoofing"
  dataTypes: ["o365"]
  reference: 
    - "https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-spoofing-protection?view=o365-worldwide"
  frequency: 60
  cache:
    - allOf:
        - field: logx.o365.Workload
          operator: "=="
          value: Exchange
        - field: logx.o365.Operation
          operator: "=="
          value: Set-DkimSigningConfig
        - field: logx.o365.ResultStatus
          operator: "in"
          value: Success,PartiallySucceeded,True
      minCount: 1
      timeLapse: 60
      save:
        - field: "logx.o365.UserId"
          alias: "SourceUser"
        - field: "logx.o365.ClientIP"
          alias: "SourceIP"
