#Rule version 1.0.0

- name: "Probable Potentially Dangerous Application detected by Bitdefender GravityZone"
  severity: "High"
  description: "This event is created whenever a potentially dangerous applications is detected and blocked on an endpoint."
  solution: "Check the logs to define if it is a real Potentially Dangerous Application or a false positive."
  category: "Impact"
  tactic: "Data Manipulation"
  dataTypes: ["antivirus-bitdefender-gz"]
  reference:
    - "https://attack.mitre.org/tactics/TA0040/"
    - "https://attack.mitre.org/techniques/T1565/"
  frequency: 60
  cache:
    - allOf:
        - field: "logx.bitdefender_gz.module"
          operator: "=="
          value: "avc"
      timeLapse: 60
      minCount: 1
      save:
        - field: "logx.bitdefender_gz.src_user"
          alias: "SourceUser"
        - field: "logx.bitdefender_gz.src_ip"
          alias: "SourceIP"
        - field: "logx.bitdefender_gz.src_port"
          alias: "SourceIP"
