# Based on Sophos Firewall 17.5+
# Rule version v1.0.3

- name: "Probable use of Low-risk applications"
  severity: Low
  description: "The Sophos firewall device has detected a use of low risked applications in enterprise environment like <strong>Xbox LIVE</strong>.
                Please see the logs attached to this alert for additional details."
  solution: "<ol>
    <li>See the logs attached to this alert to identify if this is a not an allowed use of this applications</li>
    </ol>"
  category: "Lateral Movement"
  dataTypes: ["firewall-sophos-xg"]
  reference: 
    - "https://attack.mitre.org/tactics/TA0008/"
  frequency: 60
  cache:
    - allOf:
        - field: "logx.sophos.log_subtype"
          operator: "not in"
          value: "Deny,deny,Drop,drop,Denied,denied,Dropped,dropped"
      oneOf:
        - field: "logx.sophos.application"
          operator: "regexp"
          value: "(ISAKMP VPN|WeTransfer Base|Xbox LIVE|OSC_AMU)"
        - field: "logx.sophos.application_name"
          operator: "regexp"
          value: "(ISAKMP VPN|WeTransfer Base|Xbox LIVE|OSC_AMU)"
      minCount: 1
      timeLapse: 60
      save:
        - field: "logx.sophos.proto"
          alias: "Protocol"
        - field: "logx.sophos.user_name"
          alias: "SourceUser"
        - field: "logx.sophos.src_ip"
          alias: "SourceIP"
        - field: "logx.sophos.src_port"
          alias: "SourcePort"
        - field: "logx.sophos.dest_ip"
          alias: "DestinationIP"
        - field: "logx.sophos.dest_port"
          alias: "DestinationPort"
        - field: logx.sophos.src_host
          alias: "SourceHost"
