# Based on Sophos Firewall 17.5+
# Rule version v1.0.2

- name: "Probable use of High-risk applications"
  severity: High
  description: "The Sophos firewall device has detected a use of potential risked applications in enterprise environment like <strong>Torrent Clients P2P</strong>.
                Please see the logs attached to this alert for additional details."
  solution: "<ol>
    <li>See the logs attached to this alert to identify if this is or not, an allowed use of risked applications</li>
    </ol>"
  category: "Lateral Movement"
  dataTypes: ["firewall-sophos-xg"]
  reference: 
    - "https://attack.mitre.org/tactics/TA0008/"
  frequency: 60
  cache:
    - oneOf:
        - field: "logx.sophos.application"
          operator: "regexp"
          value: "(Torrent|Proxy|EXE File Download|eMule P2P|Ares P2P)"
        - field: "logx.sophos.application_name"
          operator: "regexp"
          value: "(Torrent|Proxy|EXE File Download|eMule P2P|Ares P2P)"
      minCount: 1
      timeLapse: 60
      save:
        - field: "logx.sophos.proto"
          alias: "Protocol"
        - field: "logx.sophos.user_name"
          alias: "SourceUser"
        - field: "logx.sophos.src_ip"
          alias: "SourceIP"
        - field: "logx.sophos.src_port"
          alias: "SourcePort"
        - field: "logx.sophos.dest_ip"
          alias: "DestinationIP"
        - field: "logx.sophos.dest_port"
          alias: "DestinationPort"
        - field: logx.sophos.src_host
          alias: "SourceHost"
