- name: "AWS Config Service Tampering"
  severity: "Medium"
  description: "Identifies attempts to delete an AWS Config Service resource. An adversary may tamper with Config services in order to reduce visibility into the security posture of an account and / or its workload instances"
  solution: "Ensure proper process and file permissions are in place to prevent adversaries from disabling or interfering with security/logging services."
  category: "Impair Defenses"
  tactic: "Defense Evasion"
  dataTypes: ["aws"]
  reference:
    - "https://attack.mitre.org/tactics/TA0005/"
    - "https://attack.mitre.org/techniques/T1562/"
    - "https://docs.aws.amazon.com/config/latest/developerguide/how-does-config-work.html"
    - "https://docs.aws.amazon.com/config/latest/APIReference/API_Operations.html"
  frequency: 60
  cache:
    - allOf:
        - field: "logx.aws.cloudtrail.eventSource"
          operator: "=="
          value: "config.amazonaws.com"
      oneOf:
        - field: "logx.aws.cloudtrail.eventName"
          operator: "=="
          value: "DeleteConfigRule"
        - field: "logx.aws.cloudtrail.eventName"
          operator: "=="
          value: "DeleteOrganizationConfigRule"
        - field: "logx.aws.cloudtrail.eventName"
          operator: "=="
          value: "DeleteConfigurationAggregator"
        - field: "logx.aws.cloudtrail.eventName"
          operator: "=="
          value: "DeleteConfigurationRecorder"
        - field: "logx.aws.cloudtrail.eventName"
          operator: "=="
          value: "DeleteConformancePack"
        - field: "logx.aws.cloudtrail.eventName"
          operator: "=="
          value: "DeleteOrganizationConformancePack"
        - field: "logx.aws.cloudtrail.eventName"
          operator: "=="
          value: "DeleteDeliveryChannel"
        - field: "logx.aws.cloudtrail.eventName"
          operator: "=="
          value: "DeleteRemediationConfiguration"
        - field: "logx.aws.cloudtrail.eventName"
          operator: "=="
          value: "DeleteRetentionConfiguration"
      timeLapse: 60
      minCount: 1
      save:
        - field: logx.aws.cloudtrail.sourceIPAddress
          alias: SourceIP
        - field: logx.aws.cloudtrail.userIdentity.userName
          alias: SourceUser
