# Based on https://docs.fortinet.com/document/fortigate/7.4.1/fortios-log-message-reference/656858/log-id-definitions
# Rule version v1.0.0

- name: "FortiGate: Application blocked by Web application firewall."
  severity: "High"
  description: "This alert is triggered when the FortiGate Web Application Firewall detects and blocks an application. This implies a potential security threat in the form of a harmful or non-compliant web application."
  solution: "Investigate the source application for possible malicious behavior, as well as the ruleset of the Web Application Firewall. Ensure your firewall configuration only allows known, needed applications."
  category: "Application Layer Defense"
  tactic: "Impair Defenses"
  dataTypes: ["firewall-fortigate-traffic"]
  reference: 
    - "https://attack.mitre.org/techniques/T1562/"
    - "https://attack.mitre.org/tactics/TA0040/"
  frequency: 60
  cache:
    - allOf:
        - field: "logx.fortigate.logid"
          operator: "in"
          value: "1200030248,1201030251,1202030253,1204030255,1203030257,1205030261"
      minCount: 1
      timeLapse: 60
      save:
        - field: "logx.fortigate.proto"
          alias: "Protocol"
        - field: "logx.fortigate.user"
          alias: "SourceUser"
        - field: "logx.fortigate.src_ip"
          alias: "SourceIP"
        - field: "logx.fortigate.src_port"
          alias: "SourcePort"
        - field: "logx.fortigate.dest_ip"
          alias: "DestinationIP"
        - field: "logx.fortigate.dest_port"
          alias: "DestinationPort"
